name: sbord
dependencies:
  - python=3.7
  - pip=19.3
  - numpy=1.18
  - pip:
    - pillow==6.2.2
    - streamlit==0.64.0
    - pandas==1.1.0
    - plotly==4.9.0
    - natsort==7.0.1
    - PyYAML==5.3.1
    - scipy==1.5.2
    - -e .
